export enum CookieEvent {
  COOKIE_GET_CURRENT = "COOKIE_GET_CURRENT",
  COOKIE_SAVE = "COOKIE_SAVE",
  COOKIE_GET_SAVED_LIST = "COOKIE_GET_SAVED_LIST",
  COOKIE_DELETE = "COOKIE_DELETE",
  COOKIE_APPLY = "COOKIE_APPLY",
  COOKIE_SAVE_BY_URL = "COOKIE_SAVE_BY_URL",
  COOKIE_GET_SAVED_LIST_BY_URL = "COOKIE_GET_SAVED_LIST_BY_URL",
  COOKIE_DELETE_BY_URL = "COOKIE_DELETE_BY_URL",
  COOKIE_APPLY_BY_URL = "COOKIE_APPLY_BY_URL",
  COOKIE_UPDATE_CURRENT_URL = "COOKIE_UPDATE_CURRENT_URL",
}
