export enum MonacoEditorEvent {
  MONACO_EDITOR_GET_CONTENT = "MONACO_EDITOR_GET_CONTENT",
  MONACO_EDITOR_CONTENT_CHANGED = "MONACO_EDITOR_CONTENT_CHANGED",
}

export enum UserNotesEvent {
  USER_NOTES_GET_CONTENT = "USER_NOTES_GET_CONTENT",
  USER_NOTES_SAVE_CONTENT = "USER_NOTES_SAVE_CONTENT",
  USER_NOTES_GET_TREE = "USER_NOTES_GET_TREE",
  USER_NOTES_GET_FILE = "USER_NOTES_GET_FILE",
  USER_NOTES_SAVE_FILE = "USER_NOTES_SAVE_FILE",
  USER_NOTES_CREATE_FILE = "USER_NOTES_CREATE_FILE",
  USER_NOTES_CREATE_FOLDER = "USER_NOTES_CREATE_FOLDER",
  USER_NOTES_DELETE_NODE = "USER_NOTES_DELETE_NODE",
  USER_NOTES_RENAME_NODE = "USER_NOTES_RENAME_NODE",
  USER_NOTES_GET_CURRENT_FILE = "USER_NOTES_GET_CURRENT_FILE",
  USER_NOTES_SET_CURRENT_FILE = "USER_NOTES_SET_CURRENT_FILE",
  USER_NOTES_HISTORY_LIST = "USER_NOTES_HISTORY_LIST",
  USER_NOTES_HISTORY_GET = "USER_NOTES_HISTORY_GET",
  USER_NOTES_HISTORY_APPEND_SNAPSHOT = "USER_NOTES_HISTORY_APPEND_SNAPSHOT",
}
