export enum AppEvent {
  OPEN_EXTERNAL_URL = "OPEN_EXTERNAL_URL",
  APP_SETTINGS_GET = "APP_SETTINGS_GET",
  APP_SETTINGS_SET = "APP_SETTINGS_SET",
  WORKSPACE_APPS_GET = "WORKSPACE_APPS_GET",
  WORKSPACE_APPS_ADD = "WORKSPACE_APPS_ADD",
  WORKSPACE_APPS_REMOVE = "WORKSPACE_APPS_REMOVE",
  WORKSPACE_APP_CHECK_STATUS = "WORKSPACE_APP_CHECK_STATUS",
  WORKSPACE_APP_SELECT = "WORKSPACE_APP_SELECT",
  WORKSPACE_APPS_CHECK_NOW = "WORKSPACE_APPS_CHECK_NOW",
}
