export enum MainWindowEvent {
  GET_FILES_LIST = "GET_FILES_LIST",
  SET_SEARCH_WINDOW_HEIGHT = "SET_SEARCH_WINDOW_HEIGHT",
  GET_VSCODE_WINDOW_STATUS = "GET_VSCODE_WINDOW_STATUS",
  MAIN_WINDOW_SHOW = "MAIN_WINDOW_SHOW",
  MAIN_WINDOW_HIDE = "MAIN_WINDOW_HIDE",
  GET_VSCODE_WINDOW_FILES = "GET_VSCODE_WINDOW_FILES",
  OPEN_FILE = "OPEN_FILE",
  GET_OPEN_FILES_TIMES = "GET_OPEN_FILES_TIMES",
}
