export enum BrowserFloatingEvent {
  FLOATING_WINDOW_CREATE = "FLOATING_WINDOW_CREATE",
  FLOATING_WINDOW_SEARCH_URL = "FLOATING_WINDOW_SEARCH_URL",
  BROWSER_RECORD_NAVIGATION = "BROWSER_RECORD_NAVIGATION",
}
