export enum BrowserOverlayEvent {
  BROWSER_OVERLAY_SHOW = "BROWSER_OVERLAY_SHOW",
  BROWSER_OVERLAY_HIDE = "BROWSER_OVERLAY_HIDE",
  BROWSER_OVERLAY_CONTENT = "BROWSER_OVERLAY_CONTENT",
  BROWSER_OVERLAY_ACTION = "BROWSER_OVERLAY_ACTION",
}
