export enum BrowserSettingsEvent {
  BROWSER_LIST = "BROWSER_LIST",
  BROWSER_ADD = "BROWSER_ADD",
  BROWSER_REMOVE = "BROWSER_REMOVE",
  BROWSER_UPDATE = "BROWSER_UPDATE",
  BROWSER_REORDER = "BROWSER_REORDER",
}
