export enum BrowserWindowEvent {
  BROWSER_WINDOW_FULLSCREEN_CHANGED = "BROWSER_WINDOW_FULLSCREEN_CHANGED",
  BROWSER_WINDOW_IS_FULLSCREEN = "BROWSER_WINDOW_IS_FULLSCREEN",
  BROWSER_WINDOW_EXIT_FULLSCREEN = "BROWSER_WINDOW_EXIT_FULLSCREEN",
  BROWSER_WINDOW_MINIMIZE = "BROWSER_WINDOW_MINIMIZE",
  BROWSER_WINDOW_CLOSE_WINDOW = "BROWSER_WINDOW_CLOSE_WINDOW",
}
