export enum TerminalEvent {
  GET_STATE = "TERMINAL_GET_STATE",
  STATE_UPDATED = "TERMINAL_STATE_UPDATED",
  NEW_TAB = "TERMINAL_NEW_TAB",
  ACTIVATE_TAB = "TERMINAL_ACTIVATE_TAB",
  CLOSE_TAB = "TERMINAL_CLOSE_TAB",
}
