export enum BrowserSettingsEvent {
  BROWSER_LIST = "BROWSER_LIST",
  BROWSER_ADD = "BROWSER_ADD",
  BROWSER_REMOVE = "BROWSER_REMOVE",
  BROWSER_UPDATE = "BROWSER_UPDATE",
  BROWSER_REORDER = "BROWSER_REORDER",
}

export enum BrowserOverlayEvent {
  BROWSER_OVERLAY_SHOW = "BROWSER_OVERLAY_SHOW",
  BROWSER_OVERLAY_HIDE = "BROWSER_OVERLAY_HIDE",
  BROWSER_OVERLAY_CONTENT = "BROWSER_OVERLAY_CONTENT",
  BROWSER_OVERLAY_ACTION = "BROWSER_OVERLAY_ACTION",
}

export enum BrowserTabEvent {
  BROWSER_TAB_GET_STATE = "BROWSER_TAB_GET_STATE",
  BROWSER_TAB_STATE_UPDATED = "BROWSER_TAB_STATE_UPDATED",
  BROWSER_TAB_NEW = "BROWSER_TAB_NEW",
  BROWSER_TAB_CLOSE = "BROWSER_TAB_CLOSE",
  BROWSER_TAB_SWITCH = "BROWSER_TAB_SWITCH",
  BROWSER_TAB_NAVIGATE = "BROWSER_TAB_NAVIGATE",
  BROWSER_TAB_BACK = "BROWSER_TAB_BACK",
  BROWSER_TAB_FORWARD = "BROWSER_TAB_FORWARD",
  BROWSER_TAB_RELOAD = "BROWSER_TAB_RELOAD",
  BROWSER_TAB_REORDER = "BROWSER_TAB_REORDER",
  BROWSER_TAB_DETACH = "BROWSER_TAB_DETACH",
  BROWSER_TAB_FOCUS_ADDRESS = "BROWSER_TAB_FOCUS_ADDRESS",
  BROWSER_TAB_BLUR_ADDRESS = "BROWSER_TAB_BLUR_ADDRESS",
  BROWSER_TAB_TOGGLE_DEVTOOLS = "BROWSER_TAB_TOGGLE_DEVTOOLS",
}

export enum BrowserWindowEvent {
  BROWSER_WINDOW_FULLSCREEN_CHANGED = "BROWSER_WINDOW_FULLSCREEN_CHANGED",
  BROWSER_WINDOW_IS_FULLSCREEN = "BROWSER_WINDOW_IS_FULLSCREEN",
  BROWSER_WINDOW_EXIT_FULLSCREEN = "BROWSER_WINDOW_EXIT_FULLSCREEN",
  BROWSER_WINDOW_MINIMIZE = "BROWSER_WINDOW_MINIMIZE",
  BROWSER_WINDOW_CLOSE_WINDOW = "BROWSER_WINDOW_CLOSE_WINDOW",
}
