export enum VS_GO_EVENT {
  // 文件列表 & 搜索窗口
  GET_FILES_LIST = "GET_FILES_LIST",
  SET_SEARCH_WINDOW_HEIGHT = "SET_SEARCH_WINDOW_HEIGHT",
  GET_VSCODE_WINDOW_STATUS = "GET_VSCODE_WINDOW_STATUS",
  MAIN_WINDOW_SHOW = "MAIN_WINDOW_SHOW",
  MAIN_WINDOW_HIDE = "MAIN_WINDOW_HIDE",
  GET_VSCODE_WINDOW_FILES = "GET_VSCODE_WINDOW_FILES",
  OPEN_FILE = "OPEN_FILE",
  GET_OPEN_FILES_TIMES = "GET_OPEN_FILES_TIMES",

  // 浏览器设置
  BROWSER_LIST = "BROWSER_LIST",
  BROWSER_ADD = "BROWSER_ADD",
  BROWSER_REMOVE = "BROWSER_REMOVE",
  BROWSER_UPDATE = "BROWSER_UPDATE",
  BROWSER_REMOVE_ALL = "BROWSER_REMOVE_ALL",
  BROWSER_IMPORT_SELECT_FILE = "BROWSER_IMPORT_SELECT_FILE",
  BROWSER_IMPORT_BOOKMARKS = "BROWSER_IMPORT_BOOKMARKS",

  // 浮动窗口
  FLOATING_WINDOW_CREATE = "FLOATING_WINDOW_CREATE",
  FLOATING_WINDOW_SEARCH_URL = "FLOATING_WINDOW_SEARCH_URL",
  FLOATING_WINDOW_FOCUS_INPUT = "FLOATING_WINDOW_FOCUS_INPUT",
  FLOATING_WINDOW_TOGGLE_DEVTOOLS = "FLOATING_WINDOW_TOGGLE_DEVTOOLS",
  FLOATING_WINDOW_UPDATE_TARGET_URL = "FLOATING_WINDOW_UPDATE_TARGET_URL",
  FLOATING_WINDOW_NAVIGATION = "FLOATING_WINDOW_NAVIGATION",

  // Cookie（旧版单条）
  COOKIE_GET_CURRENT = "COOKIE_GET_CURRENT",
  COOKIE_SAVE = "COOKIE_SAVE",
  COOKIE_GET_SAVED_LIST = "COOKIE_GET_SAVED_LIST",
  COOKIE_DELETE = "COOKIE_DELETE",
  COOKIE_APPLY = "COOKIE_APPLY",

  // Cookie（基于 URL）
  COOKIE_SAVE_BY_URL = "COOKIE_SAVE_BY_URL",
  COOKIE_GET_SAVED_LIST_BY_URL = "COOKIE_GET_SAVED_LIST_BY_URL",
  COOKIE_DELETE_BY_URL = "COOKIE_DELETE_BY_URL",
  COOKIE_APPLY_BY_URL = "COOKIE_APPLY_BY_URL",

  // Cookie 管理窗口
  COOKIE_UPDATE_CURRENT_URL = "COOKIE_UPDATE_CURRENT_URL",

  // Monaco 编辑器笔记
  MONACO_EDITOR_GET_CONTENT = "MONACO_EDITOR_GET_CONTENT",
  MONACO_EDITOR_CONTENT_CHANGED = "MONACO_EDITOR_CONTENT_CHANGED",

  // 用户笔记
  USER_NOTES_GET_CONTENT = "USER_NOTES_GET_CONTENT",
  USER_NOTES_SAVE_CONTENT = "USER_NOTES_SAVE_CONTENT",

  // 用户笔记文件树
  USER_NOTES_GET_TREE = "USER_NOTES_GET_TREE",
  USER_NOTES_GET_FILE = "USER_NOTES_GET_FILE",
  USER_NOTES_SAVE_FILE = "USER_NOTES_SAVE_FILE",
  USER_NOTES_CREATE_FILE = "USER_NOTES_CREATE_FILE",
  USER_NOTES_CREATE_FOLDER = "USER_NOTES_CREATE_FOLDER",
  USER_NOTES_DELETE_NODE = "USER_NOTES_DELETE_NODE",
  USER_NOTES_RENAME_NODE = "USER_NOTES_RENAME_NODE",
  USER_NOTES_GET_CURRENT_FILE = "USER_NOTES_GET_CURRENT_FILE",
  USER_NOTES_SET_CURRENT_FILE = "USER_NOTES_SET_CURRENT_FILE",

  // 外部链接
  OPEN_EXTERNAL_URL = "OPEN_EXTERNAL_URL",

  // App 设置
  APP_SETTINGS_GET = "APP_SETTINGS_GET",
  APP_SETTINGS_SET = "APP_SETTINGS_SET",

  // 屏幕管理
  DISPLAY_GET_ALL = "DISPLAY_GET_ALL",
  DISPLAY_SET_BRIGHTNESS = "DISPLAY_SET_BRIGHTNESS",
}
