export enum VS_GO_EVENT {
    GET_FILES_LIST = 'GET_FILES_LIST',
    SET_SEARCH_WINDOW_HEIGHT = 'SET_SEARCH_WINDOW_HEIGHT',
    GET_VSCODE_WINDOW_STATUS = 'GET_VSCODE_WINDOW_STATUS',
    MAIN_WINDOW_SHOW = 'MAIN_WINDOW_SHOW',
    MAIN_WINDOW_HIDE = 'MAIN_WINDOW_HIDE',
    GET_VSCODE_WINDOW_FIELS = 'GET_VSCODE_WINDOW_FIELS',
    OPEN_FILE = 'OPEN_FILE',
    GET_OPEN_FILES_TIMES = 'GET_OPEN_FILES_TIMES',
    // 浏览器设置相关
    BROWSER_LIST = 'BROWSER_LIST',
    BROWSER_ADD = 'BROWSER_ADD',
    BROWSER_REMOVE = 'BROWSER_REMOVE',
    BROWSER_UPDATE = 'BROWSER_UPDATE',
}