export enum VS_GO_EVENT {
    GET_FILES_LIST = 'GET_FILES_LIST',
    SET_SEARCH_WINDOW_HEIGHT = 'SET_SEARCH_WINDOW_HEIGHT',
    GET_VSCODE_WINDOW_STATUS = 'GET_VSCODE_WINDOW_STATUS',
    MAIN_WINDOW_SHOW = 'MAIN_WINDOW_SHOW',
    MAIN_WINDOW_HIDE = 'MAIN_WINDOW_HIDE',
    GET_VSCODE_WINDOW_FIELS = 'GET_VSCODE_WINDOW_FIELS',
    OPEN_FILE = 'OPEN_FILE'
}